SELECT
    CAST(TPEP_PICKUP_DATETIME AS DATE) AS TRIP_DATE,
    COUNT(*) AS TOTAL_TRIPS,
    ROUND(AVG(TRIP_DISTANCE), 2) AS AVG_TRIP_DISTANCE,
    ROUND(AVG(TOTAL_AMOUNT), 2) AS AVG_FARE,
    ROUND(SUM(TOTAL_AMOUNT), 2) AS TOTAL_REVENUE
FROM {{ source('raw', 'raw_yellow_taxi_trips') }}
GROUP BY CAST(TPEP_PICKUP_DATETIME AS DATE)